###
GET http://localhost:3000/user

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"felix tito nina",
    "email":"felix@gmail.com",
    "phone":"11985522347",
    "cpf":"43047717877",
    "password":"password"
}