###
GET http://localhost:3000/user

###
GET http://localhost:3000/user/38

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"felix outlook",
    "email":"felix@outlook.com",
    "phone":"11985522347",
    "cpf":"43047717877",
    "password":"123456789"
}